#
###################################
# Site wide configuration
####################################
#
title: doapmine-bits
email: shridharmanvi@gmail.com
description: My-home.online
url: https://shridharmanvi.github.io # the base hostname & protocol for your site
keywords: ["Programming", "java", "python", "bash"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          NewYork/EST
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Shridhar Manvi
  job: "Software engineer | Data engineer"
  bio: "A software developer who loves building things and data pipelining"
  email: shridharmanvi@gmail.com
  disqus-shortname: shridharmanvi
  twitter: shridharmanvi #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: shridharmanvi #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: 5point5shots
